plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ublockdns.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.ublockdns.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "ublockdns-${variant.versionName}.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.work:work-runtime:2.8.1' // For WorkManager
    implementation 'androidx.core:core-splashscreen:1.0.1'
    
    // Gomobile native library
    implementation(name:'mobile', ext:'aar')
}
